### ISSUE TITLE
Use of undefined constant LARAVEL_START - assumed 'LARAVEL_START' (this will throw an Error in a future version of PHP)

### ISSUE THREAD

**Issue by fr3ddy** [arkaitzgarro/elastic-apm-laravel#146]
Hey,
after adding the package as describe I've tested it locally and it was working like a charm.
Now I did deploy it with Laravel Vapor onto AWS and we are getting the following errors:

```@message | {"message":"Use of undefined constant LARAVEL_START - assumed 'LARAVEL_START' (this will throw an Error in a future version of PHP)","context":{"exception":{"class":"ErrorException","message":"Use of undefined constant LARAVEL_START - assumed 'LARAVEL_START' (this will throw an Error in a future version of PHP)","code":0,"file":"/var/task/vendor/arkaitzgarro/elastic-apm-laravel/src/Collectors/FrameworkCollector.php:22"},"aws_request_id":null},"level":400,"level_name":"ERROR","channel":"development","datetime":"2021-05-20T17:22:49.808326+02:00","extra":{}}

@timestamp | 1621524169921

channel | development

context.exception.class | ErrorException

context.exception.code | 0

context.exception.file | /var/task/vendor/arkaitzgarro/elastic-apm-laravel/src/Collectors/FrameworkCollector.php:22

context.exception.message | Use of undefined constant LARAVEL_START - assumed 'LARAVEL_START' (this will throw an Error in a 
future version of PHP)

datetime | 2021-05-20T17:22:49.808326+02:00

level | 400

level_name | ERROR

message | Use of undefined constant LARAVEL_START - assumed 'LARAVEL_START' (this will throw an Error in a future version of PHP)
```

and the following (but I would assume, they are related).

```@message | {"message":"Uncaught ReflectionException: Class translator does not exist in /var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php:833\nStack trace:\n#0 /var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php(833): ReflectionClass-&gt;__construct('translator')\n#1 /var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php(714): Illuminate\\Container\\Container-&gt;build('translator')\n#2 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\\Container\\Container-&gt;resolve('translator', Array, true)\n#3 /var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php(652): Illuminate\\Foundation\\Application-&gt;resolve('translator', Array)\n#4 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(826): Illuminate\\Container\\Container-&gt;make('translator', Array)\n#5 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\\Foundation\\Application-&gt;make('translator', Array)\n#6 /var/task/vendor/","context":{"exception":{"class":"Symfony\\Component\\ErrorHandler\\Error\\FatalError","message":"Uncaught ReflectionException: Class translator does not exist in /var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php:833\nStack trace:\n#0 /var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php(833): ReflectionClass-&gt;__construct('translator')\n#1 /var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php(714): Illuminate\\Container\\Container-&gt;build('translator')\n#2 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\\Container\\Container-&gt;resolve('translator', Array, true)\n#3 /var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php(652): Illuminate\\Foundation\\Application-&gt;resolve('translator', Array)\n#4 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(826): Illuminate\\Container\\Container-&gt;make('translator', Array)\n#5 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\\Foundation\\Application-&gt;make('translator', Array)\n#6 /var/task/vendor/","code":0,"file":"/var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php:835"},"aws_request_id":null},"level":400,"level_name":"ERROR","channel":"development","datetime":"2021-05-20T17:22:49.979624+02:00","extra":{}}

@timestamp | 1621524169979

channel | development

context.exception.class | Symfony\Component\ErrorHandler\Error\FatalError

context.exception.code | 0

context.exception.file | /var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php:835

context.exception.message | Uncaught ReflectionException: Class translator does not exist in
/var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php:833Stack trace:#0 /var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php(833): ReflectionClass-&gt;__construct('translator')#1 /var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php(714): Illuminate\Container\Container-&gt;build('translator')#2 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\Container\Container-&gt;resolve('translator', Array, true)#3 /var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php(652): Illuminate\Foundation\Application-&gt;resolve('translator', Array)#4 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(826): Illuminate\Container\Container-&gt;make('translator', Array)#5 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\Foundation\Application-&gt;make('translator', Array)#6 /var/task/vendor/

datetime | 2021-05-20T17:22:49.979624+02:00

level | 400

level_name | ERROR

message | Uncaught ReflectionException: Class translator does not exist in /var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php:833Stack trace:#0 /var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php(833): ReflectionClass-&gt;__construct('translator')#1 /var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php(714): Illuminate\Container\Container-&gt;build('translator')#2 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\Container\Container-&gt;resolve('translator', Array, true)#3 /var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php(652): Illuminate\Foundation\Application-&gt;resolve('translator', Array)#4 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(826): Illuminate\Container\Container-&gt;make('translator', Array)#5 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\Foundation\Application-&gt;make('translator', Array)#6 /var/task/vendor/
```

In case anybody has experienced the same issue, I would be happy to hear your opinion on how we can solve that. My current assumption is, that due to the fact that the entry point is changing when using Laravel Vapor, the constant `LARAVEL_START` is not set.

Regards,
Frederik

**Comment by arkaitzgarro** [comment]
> My current assumption is, that due to the fact that the entry point is changing when using Laravel Vapor, the constant `LARAVEL_START` is not set.

I think your assumption is correct. The constant is defined in Laravel's [index.php](https://github.com/laravel/laravel/blob/507d499577e4f3edb51577e144b61e61de4fb57f/public/index.php#L6) file, which I also assume is not called in Vapor (I don't have experience with the platform). We also had [this issue](https://github.com/arkaitzgarro/elastic-apm-laravel/issues/145) when running the application with Octane.

I'm going to make "a fix" and set the value if the constant is not defined. The timing might not be exact, but better than making the app crash.

**Comment by arkaitzgarro** [comment]
@fr3ddy I've just released the fix. Could you install the new `v3.0.6` version and try again?

**Comment by fr3ddy** [comment]
Greate support. Thank you. Works like a charm!
