### ISSUE TITLE
Not compatiable with Lumen

### ISSUE THREAD

**Issue by lbadger** [arkaitzgarro/elastic-apm-laravel#40]
Doesn't seem to be compatiable with Lumen

```
2020/04/03 17:06:59 [error] 11#11: *3 FastCGI sent in stderr: "PHP message: [2020-04-03 17:06:59] local.ERROR: ReflectionException: Class Illuminate\Foundation\Application does not exist in /vendor/illuminate/container/Container.php:871
Stack trace:
#0 /vendor/illuminate/container/Container.php(871): ReflectionParameter->getClass()
#1 /vendor/illuminate/container/Container.php(834): Illuminate\Container\Container->resolveDependencies(Array)
#2 /vendor/illuminate/container/Container.php(681): Illuminate\Container\Container->build('AG\\ElasticApmLa...')
#3 /vendor/illuminate/container/Container.php(629): Illuminate\Container\Container->resolve('AG\\ElasticApmLa...', Array)
#4 /vendor/laravel/lumen-framework/src/Application.php(267): Illuminate\Container\Container->make('AG\\ElasticApmLa...', Array)
#5 /vendor/laravel/lumen-framework/src/helpers.php(42): Laravel\Lumen\Application->make('AG\\ElasticApmLa...', Array)
#6 /vendor/arkaitzgarro/elastic-apm-laravel/src/Agent.php(46): app('AG\\ElasticApmLa...')
#7 /vendor/arkaitzgarro/elastic-apm-laravel/src/ServiceProvider.php(96): AG\ElasticApmLaravel\Agent->registerInitCollectors()
#8 /vendor/arkaitzgarro/elastic-apm-laravel/src/ServiceProvider.php(30): AG\ElasticApmLaravel\ServiceProvider->registerInitCollectors()
#9 /vendor/laravel/lumen-framework/src/Application.php(200): AG\ElasticApmLaravel\ServiceProvider->register()
#10 /bootstrap/app.php(115): Laravel\Lumen\Application->register(Object(AG\ElasticApmLaravel\ServiceProvider))
#11 /public/index.php(13): require('/bo...')
#12 {main} {"exception":"[object] (ReflectionException(code: 0): Class Illuminate\\Foundation\\Application does not exist at /vendor/illuminate/container/Container.php:871)
```

**Comment by arkaitzgarro** [comment]
Hi @lbadger,

I have to say that we never tested the package with Lumen. Which version of the framework are you using?
